### ISSUE TITLE
Some concerns on alignment of text prompt and given conditions.

### ISSUE THREAD

**Issue by Colezwhy** [WU-CVGL/MVControl#9]
Hi, Congratulations to your wonderful work, which is very inspiring and helpful.
But after reading this paper, a question comes to me, I wonder with given conditions, can the MVControl handle text prompts that are composed of several items or contain some attaching properties or verbs? This is one prevailing issue in T2I generation.
Again, thank you for your great job.

**Comment by Colezwhy** [comment]
Also, I wanted to know for the control condition input to MVControl, what type of images do we need? For example, do we need the background to be all black or some?

**Comment by lizhiqi49** [comment]
> Hi, Congratulations to your wonderful work, which is very inspiring and helpful. But after reading this paper, a question comes to me, I wonder with given conditions, can the MVControl handle text prompts that are composed of several items or contain some attaching properties or verbs? This is one prevailing issue in T2I generation. Again, thank you for your great job.

Hi, thanks for your interest.
This work is focused on object-level generation, so it's better to have only one object in the given conditioning image. It's OK that the scene is composed tegother with multiple objects (like the rabbit sitting on bucket case or Arthur riding horse case). And it's also OK that there are several stuffs attached to the main object, like the spider man with black jacket case and winter girl with scarf case.



> Also, I wanted to know for the control condition input to MVControl, what type of images do we need? For example, do we need the background to be all black or some?

The paper shows you can use canny edge, depth map, normal map or scribble as the control conditioning image. The background of normal map should be black, and the other types of conditions do not need to consider the background.

**Comment by Colezwhy** [comment]
> > Hi, Congratulations to your wonderful work, which is very inspiring and helpful. But after reading this paper, a question comes to me, I wonder with given conditions, can the MVControl handle text prompts that are composed of several items or contain some attaching properties or verbs? This is one prevailing issue in T2I generation. Again, thank you for your great job.
> 
> Hi, thanks for your interest. This work is focused on object-level generation, so it's better to have only one object in the given conditioning image. It's OK that the scene is composed tegother with multiple objects (like the rabbit sitting on bucket case or Arthur riding horse case). And it's also OK that there are several stuffs attached to the main object, like the spider man with black jacket case and winter girl with scarf case.
> 
> > Also, I wanted to know for the control condition input to MVControl, what type of images do we need? For example, do we need the background to be all black or some?
> 
> The paper shows you can use canny edge, depth map, normal map or scribble as the control conditioning image. The background of normal map should be black, and the other types of conditions do not need to consider the background.

Thank you very much! Great job!
